export type IconTypes = 
    'image2' |
    'add-l' |
    'muban-location' |
    'muban-person' |
    'muban-blog' |
    'muban-shop' |
    'muban-flow' |
    'muban-bbs' |
    'muban-more' |
    'liebiao-more' |
    'liebiao-page' |
    'liebiao-data' |
    'liebiao-user' |
    'liebiao-site' |
    'liebiao-article' |
    'liebiao-bbs' |
    'liebiao-service' |
    'liebiao-plug' |
    'liebiao-ticket' |
    'liebiao-list' |
    'liebiao-turntable' |
    'liebiao-shoplist' |
    'link-2' |
    'sohu-news' |
    'service-info-list' |
    'kclub-Reverse-order' |
    'kclub-Positive-order' |
    'kclub-time' |
    'service-list' |
    'add-plugin' |
    'survey-survey' |
    'kkt' |
    'scrape-scrape' |
    'system_plugin-mobile_button' |
    'kuaijian-kuaijian' |
    'system_plugin-sms_button' |
    'goddenegg-goddenegg' |
    'ernie-ernie' |
    'kuaivote-kuaivote-rank' |
    'kuaivote-kuaivote-multi' |
    'kuaivote-kuaivote' |
    'system_plugin-weibo' |
    'system_plugin-title' |
    'system_plugin-weibo-min' |
    'system_plugin-qrcode-min' |
    'system_plugin-nav' |
    '18' |
    'underline-new' |
    'add-icon' |
    'info-page' |
    'more-more' |
    'system_plugin-pic' |
    'system_plugin-search' |
    'changyan-changyan' |
    'system_plugin-button' |
    'system_plugin-pictxt' |
    'system_plugin-picgroup' |
    'system_plugin-focus' |
    'system_plugin-text' |
    'system_plugin-video' |
    'system_plugin-link' |
    'system_plugin-forumlist' |
    'system_plugin-shopslist' |
    'system_plugin-commodity-list' |
    'system_plugin-topiclist' |
    'form-form' |
    'html-html' |
    'js-js' |
    'system_plugin-divider' |
    'system_plugin-layout2coloums' |
    'system_plugin-space' |
    'system_plugin-layout_floor' |
    'system_plugin-guide-follow' |
    'system_plugin-map' |
    'system_plugin-qrcode' |
    'system_plugin-share' |
    'integrals' |
    'regal' |
    'popularity' |
    'video-post' |
    'img-post' |
    'voice-post' |
    'newsection' |
    'scanqr' |
    'newarticle' |
    'setting' |
    'pause' |
    'play' |
    'radio' |
    'radio-checked' |
    'expand' |
    'add' |
    'close' |
    'star' |
    'star-o' |
    'home2' |
    'remind' |
    'envelope' |
    'angle-up' |
    'angle-down-2' |
    'image' |
    'smile' |
    'comment' |
    'scan' |
    'warning' |
    'close-2' |
    'mini' |
    'more' |
    'search' |
    'angle-down-3' |
    'voice' |
    'personal' |
    'share' |
    'watch' |
    'copy' |
    'list2' |
    'changegroup' |
    'rename' |
    'lock-o' |
    'lock' |
    'align-l' |
    'align-m' |
    'align-r' |
    'check' |
    'bold' |
    'lean' |
    'underline' |
    'link' |
    'plus' |
    'angle-down' |
    'angle-right' |
    'angle-left' |
    'phone' |
    'QQ' |
    'qq' |
    'wisdom-tooth' |
    'form' |
    'shop-list' |
    'questionnaire' |
    'service-information-list' |
    'title' |
    'big-wheel' |
    'navigation' |
    'separate' |
    'leaving-space' |
    'pictures2' |
    'keyboard' |
    'wechat' |
    'bianjiqi-T' |
    'bianjiqi-picture' |
    'bianjiqi-pictures' |
    'bianjiqi-circle' |
    'bianjiqi-link' |
    'bianjiqi-search' |
    'bianjiqi-vedio' |
    'bianjiqi-chart' |
    'bianjiqi-html' |
    'bianjiqi-js' |
    'bianjiqi-spacing' |
    'bianjiqi-cut' |
    'bianjiqi-double' |
    'bianjiqi-yinying' |
    'bianjiqi-position' |
    'bianjiqi-saoma' |
    'bianjiqi-share' |
    'bianjiqi-wechat' |
    'bianjiqi-chang' |
    'bianjiqi-heart' |
    'bianjiqi-chatlist' |
    'bianjiqi-chat' |
    'bianjiqi-shop' |
    'bianjiqi-shoplist' |
    'bianjiqi-page' |
    'bianjiqi-ticket' |
    'bianjiqi-link-2' |
    'bianjiqi-paper' |
    'bianjiqi-check-1' |
    'bianjiqi-check-2' |
    'bianjiqi-article' |
    'bianjiqi-check-3' |
    'bianjiqi-more' |
    'bianjiqi-add' |
    'bianjiqi-' |
    'bianjiqi-ticket-2' |
    'bianjiqi-ear' |
    'bianjiqi-weibo' |
    'bianjiqi-up' |
    'add-big' |
    'picture-big' |
    'download' |
    'time-01' |
    'enterprise' |
    'import' |
    'QR-code' |
    'reading-number' |
    'text' |
    'image-text' |
    'image3' |
    'arrow-up' |
    'arrow-down2' |
    '*20-02' |
    'question-new' |
    'tips' |
    'check--new-' |
    'add-new--1' |
    'question-new-1' |
    'check--new--1' |
    'user' |
    'bold-new-' |
    'italic' |
    'underline-new-1' |
    'type-new' |
    'type-new-1' |
    'type-new-2' |
    'wenzhang-up' |
    'wenzhang-down' |
    'wenzhang-suojin' |
    'wenzhang-spacing' |
    'wenzhang-right' |
    'wenzhang-left' |
    'wenzhang-center' |
    'wenzhang-brush' |
    'wenzhang-eraser' |
    'wenzhang-chart' |
    'wenzhang-I' |
    'wenzhang-I-2' |
    'wenzhang-list' |
    'wenzhang-list-2' |
    'pictures' |
    'wenzhang-pictures-2' |
    'wenzhang-link' |
    'wenzhang-link2' |
    'wenzhang-smile' |
    'wenzhang-vedio' |
    'wenzhang-shop' |
    'wenzhang-music' |
    'wenzhang-return' |
    'wenzhang-return2' |
    'wenzhang-html' |
    'user-not-logged' |
    'add-m' |
    'set-border-radius' |
    'set-padding' |
    'set-margin' |
    'lock-radius' |
    'unlock-radius' |
    'check2' |
    'warn2' |
    'up' |
    'play-2' |
    'delete' |
    'down-3' |
    'edit-3' |
    'close-3' |
    'close-4' |
    'next-3' |
    'time-3' |
    'down' |
    'rili' |
    'download-3' |
    '*14-14' |
    'arrow-down' |
    'calendar' |
    'close2' |
    'download-solid' |
    'edit' |
    'error-solid' |
    'foward-right' |
    'time' |
    'upload-solid' |
    'add-new2' |
    'close-new' |
    'help' |
    'component' |
    'pages' |
    'theme' |
    'redo' |
    'undo' |
    'copy-new' |
    'paste' |
    'pages-component' |
    'setting-new' |
    'share-new' |
    'ruler' |
    'refresh' |
    'save' |
    'preview' |
    'update-pages' |
    'create-group' |
    'create-page' |
    'search-new' |
    'page' |
    'copy2' |
    'delete2' |
    'file' |
    'close-eye' |
    'open-eye' |
    'sort2' |
    'list' |
    'sort22' |
    'loading-button' |
    'nav-pull-down' |
    'collection' |
    'pull-down' |
    'forward' |
    'home' |
    'que' |
    'success-solid' |
    'unwatch' |
    'upgrade' |
    'liebiao' |
    'shaixuan' |
    'kz-99-plugin' |
    'system_plugin-layout2coloums-min' |
    'page_plugin-down' |
    'page_plugin-up' |
    'page_plugin-right' |
    'page_plugin-left' |
    'system_plugin-button-min' |
    'system_plugin-title-min' |
    'html-html-min' |
    'js-js-min' |
    'form-form-min' |
    'copy-page' |
    'del-new' |
    'system_plugin-link-min' |
    'drop-down' |
    'drop-up' |
    'drop-right' |
    'drop-left' |
    'system_plugin-search-min' |
    'changyan-changyan-min' |
    'system_plugin-pictxt-min' |
    'system_plugin-picgroup-min' |
    'system_plugin-pic-min' |
    'system_plugin-nav-min' |
    'system_plugin-focus-min' |
    'system_plugin-text-min' |
    'edit-new' |
    'system_plugin-guide-follow-min' |
    'system_plugin-forumlist-min' |
    'system_plugin-shopslist-min' |
    'system_plugin-commodity-list-min' |
    'system_plugin-topiclist-min' |
    'system_plugin-video-min' |
    'system_plugin-divider-min' |
    'system_plugin-layout_floor-min' |
    'system_plugin-space-min' |
    'system_plugin-map-min' |
    'system_plugin-share-min' |
    'info-left' |
    'info-right' |
    'more-new' |
    'pagination-up' |
    'pagination-down' |
    'pagination-previous' |
    'pagination-next' |
    '16' |
    'lock-ratio' |
    'left-justified' |
    'center-justified' |
    'right-justified' |
    'bold-new' |
    'lean-new' |
    'add-new' |
    'info-group';